### ISSUE TITLE
enemy and player death explosions - sprite and sounds

### ISSUE THREAD

**Issue by rusty-electron** [Amegma/Space-Invaders#15]
It would be great to have explosion sprite and sounds for when the enemy or the player dies.

I think adding a `kill()` method to the ship class should do it.

**Comment by rusty-electron** [comment]
@Mayank0255 I started working on this issue yesterday and couldn't start the game. It was a type error in `collide.py` possibly introduced in #20. I have included a fix in the PR that I am preparing. The explosion visuals are done now I just need to find the right sounds, I should be able to push it by midnight.

**Comment by rusty-electron** [comment]
Ok, the issue that I was talking about in the previous comment was actually linux-specific. The code ran fine on windows but I still included the fix in the PR as including the fix doesn't affect windows but fixes issues on linux.

**Comment by Mayank0255** [comment]
> Ok, the issue that I was talking about in the previous comment was actually linux-specific. The code ran fine on windows but I still included the fix in the PR #25 as including the fix doesn't affect the working on windows but fixes issues on linux.

Good work, makes sense
